import { createMDX } from "fumadocs-mdx/next";
import type { NextConfig } from "next";

import redirects from "./src/lib/redirects.json";

const withMDX = createMDX();

const config: NextConfig = {
  reactStrictMode: true,
  images: {
    // Optimized copies are kept for a week. PDS blobs are content-addressed
    // (the CID is in the URL), so a cached copy can never go stale.
    minimumCacheTTL: 604_800,
    remotePatterns: [
      // Thumbnails for the community calls archive.
      { protocol: "https", hostname: "i.ytimg.com" },
      // Field photos on the welcome page: blobs on each uploader's PDS,
      // which can be any host, so only the blob endpoint is allowed.
      { protocol: "https", hostname: "**", pathname: "/xrpc/com.atproto.sync.getBlob" },
    ],
  },
  /**
   * Every URL GitBook served keeps working. The table is generated by
   * `scripts/migrate-gitbook.py` from the live sitemap's shape, so a link in
   * an old email or tweet lands on the same page under its new, clean slug.
   */
  async redirects() {
    return redirects;
  },
};

export default withMDX(config);
