import { createMDX } from "fumadocs-mdx/next";
import type { NextConfig } from "next";

import redirects from "./src/lib/redirects.json";

const withMDX = createMDX();

const config: NextConfig = {
  reactStrictMode: true,
  // Thumbnails for the community calls archive.
  images: { remotePatterns: [{ protocol: "https", hostname: "i.ytimg.com" }] },
  /**
   * Every URL GitBook served keeps working. The table is generated by
   * `scripts/migrate-gitbook.py` from the live sitemap's shape, so a link in
   * an old email or tweet lands on the same page under its new, clean slug.
   */
  async redirects() {
    return redirects;
  },
};

export default withMDX(config);
